FastLIO: 
  max_iteration: 3               # 卡尔曼滤波（IESKF）在单次更新中的最大迭代次数
  filter_size_surf: 0.1          # 地图面点（Surface）降采样的体素大小（单位：米）。用于控制地图的稀疏程度
  filter_size_map: 0.1           # ikd-Tree（增量式KD树）全局地图的体素降采样大小（单位：米）
  cube_side_length: 500.0        # 局部地图构建的立方体边长（单位：米）。算法只维护这个范围内的局部地图，用于状态估计，超出范围的旧点会被移除

  common:
    initial_frame: "odom"             # 初始化的时候位于的坐标系
    base_lidar_frame: "base_lidar"                # 雷达位于的坐标系
    base_link_frame: "base_link"                # 位于的坐标系
    time_sync_en: false                     # 是否开启软件时间同步。如果硬件（LiDAR和IMU）已经通过 PTP 或 PPS 同步，这里设为 false
    time_offset_lidar_to_imu: 0.0
    use_imu_odometry: true                  # true = 输出imu里程计，false = 输出lidar里程计
    imu_window_size: 5                    # imu 滑动窗口大小
    imu_time_tolerance: 0
    planar_constraint: false # 平面约束，强制设置 roll, pitch, z=0，一般不开


  preprocess:
    blind: 0.5
    lidar_type: 1 # AVIA = 1, VELO16 = 2, OUST64 = 3, MARSIM = 4
    scan_line: 4
    timestamp_unit: 3 # SEC = 0, MS = 1, US = 2, NS = 3
    scan_rate: 10
    point_filter_num: 5                     # 下采样
    feature_extract_enable: false
    
  mapping:
    acc_cov: 0.1         # IMU 加速度计的测量噪声协方差（反映传感器的精度，值越小越信任传感器数据）
    gyr_cov: 0.1         # IMU 陀螺仪的测量噪声协方差
    b_acc_cov: 0.0001    # 加速度计零偏（Bias）的随机游走噪声协方差（反映零偏随时间漂移的速度）
    b_gyr_cov: 0.0001    # 陀螺仪零偏（Bias）的随机游走噪声协方差
    fov_degree:    360.0 # 激光雷达的视场角（FOV），单位：度
    det_range:     100.0 # 激光雷达的最大有效探测距离，单位：米
    
    extrinsic_est_en:  false   # 是否开启在线外参估计。True 表示算法会在运行中自动微调 LiDAR 和 IMU 之间的相对位姿
    extrinsic_T: [ -0.011, -0.02329, 0.04412 ] # 外参平移向量 [x, y, z]，单位：米。即 LiDAR 坐标系原点在 IMU 坐标系下的位置
    extrinsic_R: [1, 0.0, 0,
                   0.0,    1.0, 0.0,
                  0, 0.0, 1 ]
